# Docker Compose para Controle Financeiro PWA
# Versão otimizada para desenvolvimento e produção

version: '3.8'

services:
  # Serviço principal da aplicação
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    
    # Nome do container
    container_name: controle-financeiro-pwa
    
    # Restart automático
    restart: unless-stopped
    
    # Mapeamento de portas
    ports:
      - "8080:8080"
    
    # Volumes para desenvolvimento (hot reload)
    volumes:
      # Mapear pasta src para desenvolvimento
      - ./src:/usr/share/nginx/html:ro
      # Mapear configuração nginx (caso precise alterar)
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    
    # Variáveis de ambiente
    environment:
      - NODE_ENV=development
      - PWA_VERSION=1.0.0
      - PWA_NAME=Controle Financeiro
    
    # Health check
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    
    # Labels para organização
    labels:
      - "app.name=controle-financeiro-pwa"
      - "app.version=1.0.0"
      - "app.maintainer=cristopherlima-dev"
      - "app.description=PWA para Controle Financeiro Pessoal"

# Networks (se precisarmos de outros serviços futuramente)
networks:
  default:
    name: controle-financeiro-network

# Volumes nomeados (se precisarmos de persistência futuramente)
volumes:
  # Volume para dados persistentes (futuro)
  app_data:
    driver: local
    labels:
      - "app.data=controle-financeiro-pwa"